language: php

php:
  - '8.2'

before_install:
  - sudo add-apt-repository ppa:ondrej/php -y  # Add Ondřej Surý's PPA for PHP versions
  - sudo apt-get update  # Update package lists to include the new PHP version
  - sudo apt-get install -y php8.2 php8.2-cli php8.2-common php8.2-mbstring php8.2-xml php8.2-curl  # Install PHP 8.2 and necessary extensions
  - sudo update-alternatives --set php /usr/bin/php8.2  # Set PHP 8.2 as the default version
  - php --version  # Verify the installed PHP version

install:
  - composer install --no-interaction --prefer-dist --optimize-autoloader

script:
  - vendor/bin/phpunit --configuration phpunit.xml

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
