dist: focal  # or another recent version like bionic
language: php

php:
  - '8.2'

env:
  - DB=mariadb
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

before_install:
  - |
    if [[ "$COVERAGE" != "1" ]]; then
      phpenv config-rm ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || echo "xdebug is not installed"
    fi
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - travis_retry composer self-update
  - composer clear-cache

install:
  - rm composer.lock
  - travis_retry composer update --no-interaction --prefer-dist --no-suggest --no-progress

script:
  - |
    if [[ "$DB" == "mysql" || "$DB" == "mariadb" ]]; then
      mysql -e "CREATE SCHEMA doctrine_tests; GRANT ALL PRIVILEGES ON doctrine_tests.* to travis@'%'";
    fi
  - ENABLE_SECOND_LEVEL_CACHE=0 ./vendor/bin/phpunit -v -c tests/travis/$DB.travis.xml

cache:
  directories:
    - $HOME/.composer/cache

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
