language: php

php:
  - '8.2'

before_install:
  - sudo add-apt-repository ppa:ondrej/php -y  # Add Ondřej Surý's PPA for PHP versions
  - sudo apt-get update  # Update package lists to include the new PHP version
  - sudo apt-get install -y libonig-dev  # Install libonig for mbstring support
  - sudo apt-get install -y php8.2-mbstring php8.2-xml php8.2-curl  # Ensure necessary PHP extensions are installed
  - php -m  # Show installed PHP modules for debugging

install:
  - composer install --no-interaction --prefer-dist --optimize-autoloader

script:
  - vendor/bin/phpunit --configuration phpunit.xml

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
