language: php

php:
  - '8.2'

before_install:
  - sudo add-apt-repository ppa:ondrej/php -y  # Add PHP 8.2 repository
  - sudo apt-get update
  - sudo apt-get install -y php8.2 php8.2-cli php8.2-common php8.2-mbstring php8.2-xml php8.2-curl
  - sudo update-alternatives --set php /usr/bin/php8.2  # Set PHP 8.2 globally
  - php --version  # Confirm PHP 8.2 is being used

install:
  - composer install --no-interaction --prefer-dist --optimize-autoloader

script:
  - vendor/bin/phpunit --configuration phpunit.xml

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
