language: php

php:
  - '8.2'

before_install:
  - sudo apt-get update
  - sudo apt-get install -y software-properties-common  # Install software-properties-common if not already present
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get update
  - sudo apt-get install -y libonig-dev
  - sudo apt-get install -y php8.2 php8.2-cli php8.2-common php8.2-mbstring php8.2-xml php8.2-curl

install:
  - composer install --no-interaction --prefer-dist --optimize-autoloader

script:
  - vendor/bin/phpunit --configuration phpunit.xml

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
