<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function show($slug)
    {
        $images = [];

        if ($slug === 'xohanoc') {
            $images = [
                ['id' => 0, 'url' => 'images/xohanoc/xohanoc1.webp'],
                ['id' => 1, 'url' => 'images/xohanoc/xohanoc2.webp'],
                ['id' => 2, 'url' => 'images/xohanoc/xohanoc3.webp'],
                ['id' => 3, 'url' => 'images/xohanoc/xohanoc4.webp'],
                ['id' => 4, 'url' => 'images/xohanoc/xohanoc5.webp'],
                ['id' => 5, 'url' => 'images/xohanoc/xohanoc6.webp'],
                ['id' => 6, 'url' => 'images/xohanoc/xohanoc7.webp'],
                ['id' => 7, 'url' => 'images/xohanoc/xohanoc8.webp'],
                ['id' => 8, 'url' => 'images/xohanoc/xohanoc9.webp'],
                ['id' => 9, 'url' => 'images/xohanoc/xohanoc10.webp'],
                ['id' => 10, 'url' => 'images/xohanoc/xohanoc11.webp'],
                ['id' => 11, 'url' => 'images/xohanoc/xohanoc12.webp'],
                ['id' => 12, 'url' => 'images/xohanoc/xohanoc13.webp'],
                ['id' => 13, 'url' => 'images/xohanoc/xohanoc14.webp'],
                ['id' => 14, 'url' => 'images/xohanoc/xohanoc15.webp'],
                ['id' => 15, 'url' => 'images/xohanoc/xohanoc16.webp'],
                ['id' => 16, 'url' => 'images/xohanoc/xohanoc17.webp'],
                ['id' => 17, 'url' => 'images/xohanoc/xohanoc18.webp'],
                ['id' => 18, 'url' => 'images/xohanoc/xohanoc19.webp'],
                ['id' => 19, 'url' => 'images/xohanoc/xohanoc20.webp'],
                ['id' => 20, 'url' => 'images/xohanoc/xohanoc21.webp'],
                ['id' => 21, 'url' => 'images/xohanoc/xohanoc22.webp'],
                ['id' => 22, 'url' => 'images/xohanoc/xohanoc23.webp'],
                ['id' => 23, 'url' => 'images/xohanoc/xohanoc24.webp'],
                ['id' => 24, 'url' => 'images/xohanoc/xohanoc25.webp'],
                ['id' => 25, 'url' => 'images/xohanoc/xohanoc26.webp'],
                ['id' => 26, 'url' => 'images/xohanoc/xohanoc27.webp'],
                ['id' => 27, 'url' => 'images/xohanoc/xohanoc28.webp'],
                ['id' => 28, 'url' => 'images/xohanoc/xohanoc29.webp'],
                ['id' => 29, 'url' => 'images/xohanoc/xohanoc30.webp'],
                ['id' => 30, 'url' => 'images/xohanoc/xohanoc31.webp'],
                ['id' => 31, 'url' => 'images/xohanoc/xohanoc32.webp'],
                ['id' => 32, 'url' => 'images/xohanoc/xohanoc33.webp'],
                ['id' => 33, 'url' => 'images/xohanoc/xohanoc34.webp'],
                ['id' => 34, 'url' => 'images/xohanoc/xohanoc35.webp'],
                ['id' => 35, 'url' => 'images/xohanoc/xohanoc36.webp'],
                ['id' => 36, 'url' => 'images/xohanoc/xohanoc37.webp'],
                ['id' => 37, 'url' => 'images/xohanoc/xohanoc38.webp'],
                ['id' => 38, 'url' => 'images/xohanoc/xohanoc39.webp'],
                ['id' => 39, 'url' => 'images/xohanoc/xohanoc40.webp'],
                ['id' => 40, 'url' => 'images/xohanoc/xohanoc41.webp'],
                ['id' => 41, 'url' => 'images/xohanoc/xohanoc42.webp'],
                ['id' => 42, 'url' => 'images/xohanoc/xohanoc43.webp'],
                ['id' => 43, 'url' => 'images/xohanoc/xohanoc44.webp'],
                ['id' => 44, 'url' => 'images/xohanoc/xohanoc45.webp'],
                ['id' => 45, 'url' => 'images/xohanoc/xohanoc46.webp'],
                ['id' => 46, 'url' => 'images/xohanoc/xohanoc47.webp'],
                ['id' => 47, 'url' => 'images/xohanoc/xohanoc48.webp'],
                ['id' => 48, 'url' => 'images/xohanoc/xohanoc49.webp'],
                ['id' => 49, 'url' => 'images/xohanoc/xohanoc50.webp'],
                ['id' => 50, 'url' => 'images/xohanoc/xohanoc51.webp'],
                ['id' => 51, 'url' => 'images/xohanoc/xohanoc52.webp'],
                ['id' => 52, 'url' => 'images/xohanoc/xohanoc53.webp'],
                ['id' => 53, 'url' => 'images/xohanoc/xohanoc54.webp'],
                ['id' => 54, 'url' => 'images/xohanoc/xohanoc55.webp'],
                ['id' => 55, 'url' => 'images/xohanoc/xohanoc56.webp'],
                ['id' => 56, 'url' => 'images/xohanoc/xohanoc57.webp'],
                ['id' => 57, 'url' => 'images/xohanoc/xohanoc58.webp'],
                ['id' => 58, 'url' => 'images/xohanoc/xohanoc59.webp'],
                ['id' => 59, 'url' => 'images/xohanoc/xohanoc60.webp'],
                ['id' => 60, 'url' => 'images/xohanoc/xohanoc61.webp'],
                ['id' => 61, 'url' => 'images/xohanoc/xohanoc62.webp'],
                ['id' => 62, 'url' => 'images/xohanoc/xohanoc63.webp'],
                ['id' => 63, 'url' => 'images/xohanoc/xohanoc64.webp'],
                ['id' => 64, 'url' => 'images/xohanoc/xohanoc65.webp'],
                ['id' => 65, 'url' => 'images/xohanoc/xohanoc66.webp'],
                ['id' => 66, 'url' => 'images/xohanoc/xohanoc67.webp'],
                ['id' => 67, 'url' => 'images/xohanoc/xohanoc68.webp'],
                ['id' => 68, 'url' => 'images/xohanoc/xohanoc69.webp'],
                ['id' => 69, 'url' => 'images/xohanoc/xohanoc70.webp'],
                ['id' => 70, 'url' => 'images/xohanoc/xohanoc71.webp'],
                ['id' => 71, 'url' => 'images/xohanoc/xohanoc72.webp'],
                ['id' => 72, 'url' => 'images/xohanoc/xohanoc73.webp'],
                ['id' => 73, 'url' => 'images/xohanoc/xohanoc74.webp'],
                ['id' => 74, 'url' => 'images/xohanoc/xohanoc75.webp'],
                ['id' => 75, 'url' => 'images/xohanoc/xohanoc76.webp'],
            ];
        } elseif ($slug === 'sanhanguyc') {
            $images = [
                ['id' => 0, 'url' => 'images/sanhanguyc/sanhanguyc1.webp'],
                ['id' => 1, 'url' => 'images/sanhanguyc/sanhanguyc2.webp'],
                ['id' => 2, 'url' => 'images/sanhanguyc/sanhanguyc3.webp'],
                ['id' => 3, 'url' => 'images/sanhanguyc/sanhanguyc4.webp'],
                ['id' => 4, 'url' => 'images/sanhanguyc/sanhanguyc5.webp'],
                ['id' => 5, 'url' => 'images/sanhanguyc/sanhanguyc6.webp'],
                ['id' => 6, 'url' => 'images/sanhanguyc/sanhanguyc7.webp'],
                ['id' => 7, 'url' => 'images/sanhanguyc/sanhanguyc8.webp'],
                ['id' => 8, 'url' => 'images/sanhanguyc/sanhanguyc9.webp'],
                ['id' => 9, 'url' => 'images/sanhanguyc/sanhanguyc10.webp'],
                ['id' => 10, 'url' => 'images/sanhanguyc/sanhanguyc11.webp'],
                ['id' => 11, 'url' => 'images/sanhanguyc/sanhanguyc12.webp'],
                ['id' => 12, 'url' => 'images/sanhanguyc/sanhanguyc13.webp'],
                ['id' => 13, 'url' => 'images/sanhanguyc/sanhanguyc14.webp'],
                ['id' => 14, 'url' => 'images/sanhanguyc/sanhanguyc15.webp'],
                ['id' => 15, 'url' => 'images/sanhanguyc/sanhanguyc16.webp'],
                ['id' => 16, 'url' => 'images/sanhanguyc/sanhanguyc17.webp'],
                ['id' => 17, 'url' => 'images/sanhanguyc/sanhanguyc18.webp'],
                ['id' => 18, 'url' => 'images/sanhanguyc/sanhanguyc19.webp'],
                ['id' => 19, 'url' => 'images/sanhanguyc/sanhanguyc20.webp'],
                ['id' => 20, 'url' => 'images/sanhanguyc/sanhanguyc21.webp'],
                ['id' => 21, 'url' => 'images/sanhanguyc/sanhanguyc22.webp'],
                ['id' => 22, 'url' => 'images/sanhanguyc/sanhanguyc23.webp'],
                ['id' => 23, 'url' => 'images/sanhanguyc/sanhanguyc24.webp'],
                ['id' => 24, 'url' => 'images/sanhanguyc/sanhanguyc25.webp'],
                ['id' => 25, 'url' => 'images/sanhanguyc/sanhanguyc26.webp'],
            ];
        } elseif ($slug === "hyurasenyak"){
            $images = [
                ['id' => 0, 'url' => 'images/hyurasenyak/hyurasenyak1.webp'],
                ['id' => 1, 'url' => 'images/hyurasenyak/hyurasenyak2.webp'],
                ['id' => 2, 'url' => 'images/hyurasenyak/hyurasenyak3.webp'],
                ['id' => 3, 'url' => 'images/hyurasenyak/hyurasenyak4.webp'],
                ['id' => 4, 'url' => 'images/hyurasenyak/hyurasenyak5.webp'],
                ['id' => 5, 'url' => 'images/hyurasenyak/hyurasenyak6.webp'],
                ['id' => 6, 'url' => 'images/hyurasenyak/hyurasenyak7.webp'],
                ['id' => 7, 'url' => 'images/hyurasenyak/hyurasenyak8.webp'],
                ['id' => 8, 'url' => 'images/hyurasenyak/hyurasenyak9.webp'],
                ['id' => 9, 'url' => 'images/hyurasenyak/hyurasenyak10.webp'],
                ['id' => 10, 'url' => 'images/hyurasenyak/hyurasenyak11.webp'],
                ['id' => 11, 'url' => 'images/hyurasenyak/hyurasenyak12.webp'],
                ['id' => 12, 'url' => 'images/hyurasenyak/hyurasenyak13.webp'],
                ['id' => 13, 'url' => 'images/hyurasenyak/hyurasenyak14.webp'],
                ['id' => 14, 'url' => 'images/hyurasenyak/hyurasenyak16.webp'],
                ['id' => 15, 'url' => 'images/hyurasenyak/hyurasenyak17.webp'],
                ['id' => 16, 'url' => 'images/hyurasenyak/hyurasenyak18.webp'],
                ['id' => 17, 'url' => 'images/hyurasenyak/hyurasenyak19.webp'],
                ['id' => 18, 'url' => 'images/hyurasenyak/hyurasenyak20.webp'],
                ['id' => 19, 'url' => 'images/hyurasenyak/hyurasenyak21.webp'],
            ];
        } elseif ($slug === "nnjasenyak"){
            $images = [
                ['id' => 0, 'url' => 'images/nnjasenyak/nnjasenyak1.webp'],
                ['id' => 1, 'url' => 'images/nnjasenyak/nnjasenyak2.webp'],
                ['id' => 2, 'url' => 'images/nnjasenyak/nnjasenyak3.webp'],
                ['id' => 3, 'url' => 'images/nnjasenyak/nnjasenyak4.webp'],
                ['id' => 4, 'url' => 'images/nnjasenyak/nnjasenyak5.webp'],
                ['id' => 5, 'url' => 'images/nnjasenyak/nnjasenyak6.webp'],
                ['id' => 6, 'url' => 'images/nnjasenyak/nnjasenyak7.webp'],
                ['id' => 7, 'url' => 'images/nnjasenyak/nnjasenyak8.webp'],
                ['id' => 8, 'url' => 'images/nnjasenyak/nnjasenyak9.webp'],
                ['id' => 9, 'url' => 'images/nnjasenyak/nnjasenyak10.webp'],
                ['id' => 10, 'url' => 'images/nnjasenyak/nnjasenyak11.webp'],
                ['id' => 11, 'url' => 'images/nnjasenyak/nnjasenyak12.webp'],
                ['id' => 12, 'url' => 'images/nnjasenyak/nnjasenyak13.webp'],
                ['id' => 13, 'url' => 'images/nnjasenyak/nnjasenyak14.webp'],
                ['id' => 14, 'url' => 'images/nnjasenyak/nnjasenyak15.webp'],
                ['id' => 15, 'url' => 'images/nnjasenyak/nnjasenyak16.webp'],
                ['id' => 16, 'url' => 'images/nnjasenyak/nnjasenyak17.webp'],
                ['id' => 17, 'url' => 'images/nnjasenyak/nnjasenyak18.webp'],
                ['id' => 18, 'url' => 'images/nnjasenyak/nnjasenyak19.webp'],
                ['id' => 19, 'url' => 'images/nnjasenyak/nnjasenyak20.webp'],
                ['id' => 20, 'url' => 'images/nnjasenyak/nnjasenyak21.webp'],
                ['id' => 21, 'url' => 'images/nnjasenyak/nnjasenyak22.webp'],
                ['id' => 22, 'url' => 'images/nnjasenyak/nnjasenyak23.webp'],
                ['id' => 23, 'url' => 'images/nnjasenyak/nnjasenyak24.webp'],
                ['id' => 24, 'url' => 'images/nnjasenyak/nnjasenyak25.webp'],
                ['id' => 25, 'url' => 'images/nnjasenyak/nnjasenyak26.webp'],
                ['id' => 26, 'url' => 'images/nnjasenyak/nnjasenyak27.webp'],
                ['id' => 27, 'url' => 'images/nnjasenyak/nnjasenyak28.webp'],
                ['id' => 28, 'url' => 'images/nnjasenyak/nnjasenyak29.webp'],
                ['id' => 29, 'url' => 'images/nnjasenyak/nnjasenyak30.webp'],
                ['id' => 30, 'url' => 'images/nnjasenyak/nnjasenyak31.webp'],
                ['id' => 31, 'url' => 'images/nnjasenyak/nnjasenyak32.webp'],
                ['id' => 32, 'url' => 'images/nnjasenyak/nnjasenyak33.webp'],
                ['id' => 33, 'url' => 'images/nnjasenyak/nnjasenyak34.webp'],
                ['id' => 34, 'url' => 'images/nnjasenyak/nnjasenyak35.webp'],
                ['id' => 35, 'url' => 'images/nnjasenyak/nnjasenyak36.webp'],
                ['id' => 36, 'url' => 'images/nnjasenyak/nnjasenyak37.webp'],
                ['id' => 37, 'url' => 'images/nnjasenyak/nnjasenyak38.webp'],
                ['id' => 38, 'url' => 'images/nnjasenyak/nnjasenyak39.webp'],
                ['id' => 39, 'url' => 'images/nnjasenyak/nnjasenyak40.webp'],
                ['id' => 40, 'url' => 'images/nnjasenyak/nnjasenyak41.webp'],
                ['id' => 41, 'url' => 'images/nnjasenyak/nnjasenyak42.webp'],
                ['id' => 42, 'url' => 'images/nnjasenyak/nnjasenyak43.webp'],
                ['id' => 43, 'url' => 'images/nnjasenyak/nnjasenyak44.webp'],
                ['id' => 44, 'url' => 'images/nnjasenyak/nnjasenyak45.webp'],
                ['id' => 45, 'url' => 'images/nnjasenyak/nnjasenyak46.webp'],
                ['id' => 46, 'url' => 'images/nnjasenyak/nnjasenyak47.webp'],
                ['id' => 47, 'url' => 'images/nnjasenyak/nnjasenyak48.webp'],
                ['id' => 48, 'url' => 'images/nnjasenyak/nnjasenyak49.webp'],
                ['id' => 49, 'url' => 'images/nnjasenyak/nnjasenyak50.webp'],
                ['id' => 50, 'url' => 'images/nnjasenyak/nnjasenyak51.webp'],
                ['id' => 51, 'url' => 'images/nnjasenyak/nnjasenyak52.webp'],
                ['id' => 52, 'url' => 'images/nnjasenyak/nnjasenyak53.webp'],
                ['id' => 53, 'url' => 'images/nnjasenyak/nnjasenyak54.webp'],
                ['id' => 54, 'url' => 'images/nnjasenyak/nnjasenyak55.webp'],
                ['id' => 55, 'url' => 'images/nnjasenyak/nnjasenyak56.webp'],
                ['id' => 56, 'url' => 'images/nnjasenyak/nnjasenyak57.webp'],
                ['id' => 57, 'url' => 'images/nnjasenyak/nnjasenyak58.webp'],
                ['id' => 58, 'url' => 'images/nnjasenyak/nnjasenyak59.webp'],
                ['id' => 59, 'url' => 'images/nnjasenyak/nnjasenyak60.webp'],
                ['id' => 60, 'url' => 'images/nnjasenyak/nnjasenyak61.webp'],
                ['id' => 61, 'url' => 'images/nnjasenyak/nnjasenyak62.webp'],
                ['id' => 62, 'url' => 'images/nnjasenyak/nnjasenyak63.webp'],
                ['id' => 63, 'url' => 'images/nnjasenyak/nnjasenyak64.webp'],
                ['id' => 64, 'url' => 'images/nnjasenyak/nnjasenyak65.webp'],
                ['id' => 65, 'url' => 'images/nnjasenyak/nnjasenyak66.webp'],
                ['id' => 66, 'url' => 'images/nnjasenyak/nnjasenyak67.webp'],
                ['id' => 67, 'url' => 'images/nnjasenyak/nnjasenyak68.webp'],
                ['id' => 68, 'url' => 'images/nnjasenyak/nnjasenyak69.webp'],
                ['id' => 69, 'url' => 'images/nnjasenyak/nnjasenyak70.webp'],
                ['id' => 70, 'url' => 'images/nnjasenyak/nnjasenyak71.webp'],
                ['id' => 71, 'url' => 'images/nnjasenyak/nnjasenyak72.webp'],
                ['id' => 72, 'url' => 'images/nnjasenyak/nnjasenyak73.webp'],
                ['id' => 73, 'url' => 'images/nnjasenyak/nnjasenyak74.webp'],
                ['id' => 74, 'url' => 'images/nnjasenyak/nnjasenyak75.webp'],
            ];
        } elseif ($slug === 'ofisayin') {
            $images = [
                ['id' => 0, 'url' => 'images/ofisayin/ofisayin1.webp'],
                ['id' => 1, 'url' => 'images/ofisayin/ofisayin2.webp'],
                ['id' => 2, 'url' => 'images/ofisayin/ofisayin3.webp'],
                ['id' => 3, 'url' => 'images/ofisayin/ofisayin4.webp'],
                ['id' => 4, 'url' => 'images/ofisayin/ofisayin5.webp'],
                ['id' => 5, 'url' => 'images/ofisayin/ofisayin6.webp'],
                ['id' => 6, 'url' => 'images/ofisayin/ofisayin7.webp'],
                ['id' => 7, 'url' => 'images/ofisayin/ofisayin8.webp'],
                ['id' => 8, 'url' => 'images/ofisayin/ofisayin9.webp'],
                ['id' => 9, 'url' => 'images/ofisayin/ofisayin10.webp'],
                ['id' => 10, 'url' => 'images/ofisayin/ofisayin11.webp'],
                ['id' => 11, 'url' => 'images/ofisayin/ofisayin12.webp'],
                ['id' => 12, 'url' => 'images/ofisayin/ofisayin13.webp'],
                ['id' => 13, 'url' => 'images/ofisayin/ofisayin14.webp'],
                ['id' => 14, 'url' => 'images/ofisayin/ofisayin15.webp'],
                ['id' => 15, 'url' => 'images/ofisayin/ofisayin16.webp'],
                ['id' => 16, 'url' => 'images/ofisayin/ofisayin17.webp'],
                ['id' => 17, 'url' => 'images/ofisayin/ofisayin18.webp'],
                ['id' => 18, 'url' => 'images/ofisayin/ofisayin19.webp'],
                ['id' => 19, 'url' => 'images/ofisayin/ofisayin20.webp'],
            ];
        }  elseif ($slug === 'pati') {
            $images = [
                ['id' => 0, 'url' => 'images/pati/pati1.webp'],
                ['id' => 1, 'url' => 'images/pati/pati2.webp'],
                ['id' => 2, 'url' => 'images/pati/pati3.webp'],
                ['id' => 3, 'url' => 'images/pati/pati4.webp'],
                ['id' => 4, 'url' => 'images/pati/pati5.webp'],
                ['id' => 5, 'url' => 'images/pati/pati6.webp'],
                ['id' => 6, 'url' => 'images/pati/pati7.webp'],
                ['id' => 7, 'url' => 'images/pati/pati8.webp'],
                ['id' => 8, 'url' => 'images/pati/pati9.webp'],
            ];
        }  elseif ($slug === 'mankakan') {
            $images = [
                ['id' => 0, 'url' => 'images/mankakan/mankakan1.webp'],
                ['id' => 1, 'url' => 'images/mankakan/mankakan2.webp'],
                ['id' => 2, 'url' => 'images/mankakan/mankakan3.webp'],
                ['id' => 3, 'url' => 'images/mankakan/mankakan4.webp'],
                ['id' => 4, 'url' => 'images/mankakan/mankakan5.webp'],
                ['id' => 5, 'url' => 'images/mankakan/mankakan6.webp'],
                ['id' => 6, 'url' => 'images/mankakan/mankakan7.webp'],
                ['id' => 7, 'url' => 'images/mankakan/mankakan8.webp'],
                ['id' => 8, 'url' => 'images/mankakan/mankakan9.webp'],
                ['id' => 9, 'url' => 'images/mankakan/mankakan10.webp'],
                ['id' => 10, 'url' => 'images/mankakan/mankakan11.webp'],
                ['id' => 11, 'url' => 'images/mankakan/mankakan12.webp'],
                ['id' => 12, 'url' => 'images/mankakan/mankakan13.webp'],
                ['id' => 13, 'url' => 'images/mankakan/mankakan14.webp'],
                ['id' => 14, 'url' => 'images/mankakan/mankakan15.webp'],
                ['id' => 15, 'url' => 'images/mankakan/mankakan16.webp'],
                ['id' => 16, 'url' => 'images/mankakan/mankakan17.webp'],
                ['id' => 17, 'url' => 'images/mankakan/mankakan18.webp'],
                ['id' => 18, 'url' => 'images/mankakan/mankakan19.webp'],
                ['id' => 19, 'url' => 'images/mankakan/mankakan20.webp'],
                ['id' => 20, 'url' => 'images/mankakan/mankakan21.webp'],
                ['id' => 21, 'url' => 'images/mankakan/mankakan22.webp'],
                ['id' => 22, 'url' => 'images/mankakan/mankakan23.webp'],
                ['id' => 23, 'url' => 'images/mankakan/mankakan24.webp'],
                ['id' => 24, 'url' => 'images/mankakan/mankakan25.webp'],
                ['id' => 25, 'url' => 'images/mankakan/mankakan26.webp'],
                ['id' => 26, 'url' => 'images/mankakan/mankakan27.webp'],
                ['id' => 27, 'url' => 'images/mankakan/mankakan28.webp'],
                ['id' => 28, 'url' => 'images/mankakan/mankakan29.webp'],
            ];
        }
        else {
            abort(404);
        }

        return view('categories.' . $slug, compact('images'));
    }
}
